# Generated by Django 3.2.5 on 2021-07-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='video_type',
            field=models.CharField(choices=[('Series', 'Series'), ('Movie', 'Movie')], default='Movie', max_length=11),
        ),
    ]
