# Generated by Django 3.2.5 on 2021-07-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_main', '0002_watchlist_video_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='video_type',
        ),
    ]
