# Generated by Django 3.2.5 on 2021-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_main', '0003_remove_watchlist_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='watch_later',
            field=models.BooleanField(default=False),
        ),
    ]
