# Generated by Django 3.2.5 on 2021-07-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_main', '0004_auto_20210718_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='watch_later',
        ),
        migrations.RemoveField(
            model_name='series',
            name='watch_later',
        ),
    ]
