# Generated by Django 3.2.5 on 2021-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_main', '0005_auto_20210718_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, default='Recommended', related_name='movie_tags', to='video_main.Tag'),
        ),
    ]
