# Generated by Django 3.2.5 on 2021-07-26 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video_main', '0007_auto_20210726_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
