# Generated by Django 3.2.5 on 2021-07-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_main', '0008_auto_20210726_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movie_tags', to='video_main.Tag'),
        ),
    ]
