# Generated by Django 3.2.5 on 2021-07-23 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_controller', '0004_userprofile_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='about',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='caption',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='...', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
